x-default-agents: &default-agents
  agents:
    queue: "default"

env:
  SVMKIT_DIR:            "./svmkit"
  PULUMI_SVMKIT_DIR:     "./pulumi-svmkit"
  SVMKIT_EXAMPLES_DIR:   .
  PULUMI_ACCESS_TOKEN:   "${PULUMI_ACCESS_TOKEN}"
  AWS_ACCESS_KEY_ID:     "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  AWS_DEFAULT_REGION:    "us-west-2"
  
steps:
  - key: setup
    label: ":rocket: Setup test-svmkit"
    <<: *default-agents
    commands:
      - pwd
      - ls -l
      - git clone https://github.com/abklabs/svmkit     ./svmkit
      - ls -l 
      - git clone https://github.com/abklabs/pulumi-svmkit ./pulumi-svmkit
      - ls -l 
      - chmod +x ./tests/test-svmkit
      - echo Running test-svmkit --setup-only
      - ./tests/test-svmkit --setup-only
      - ls pulumi-svmkit/sdk/
      - tar -zcf pulumi-sdk.tgz pulumi-svmkit/sdk
      
    artifact_paths:
      - pulumi-sdk.tgz
      
  - label: ":heavy_check_mark: Test aws-network-spe-py"
    depends_on: ["setup"]
    <<: *default-agents
    plugins:
      - artifacts:
          download:
             - pulumi-sdk.tgz
    commands:
      - git clone https://github.com/abklabs/svmkit     ./svmkit
      - git clone https://github.com/dantedelucia/buildkite-svmkit-examples.git ./svmkit-examples
      - tar zxf pulumi-sdk.tgz
      - ./tests/test-svmkit test-aws-network-spe-py

  - label: ":heavy_check_mark: Test aws-validator-fd-ts"
    depends_on: ["setup"]
    <<: *default-agents
    plugins:
      - artifacts:
          download:
             - pulumi-sdk.tgz
    commands:
      - git clone https://github.com/abklabs/svmkit     ./svmkit          
      - git clone https://github.com/dantedelucia/buildkite-svmkit-examples.git ./svmkit-examples
      - tar zxf pulumi-sdk.tgz      
      - ./tests/test-svmkit test-aws-validator-fd-ts

  - label: ":heavy_check_mark: Test aws-validator-agave-ts"
    depends_on: ["setup"]
    <<: *default-agents
    plugins:
      - artifacts:
          download:
             - pulumi-sdk.tgz
    commands:
      - git clone https://github.com/abklabs/svmkit     ./svmkit          
      - git clone https://github.com/dantedelucia/buildkite-svmkit-examples.git ./svmkit-examples
      - tar zxf pulumi-sdk.tgz      
      - ./tests/test-svmkit test-aws-validator-agave-ts
