x-default-agents: &default-agents
  agents:
    queue: "default"
    
x-test-template: &test-template
  <<: *default-agents
  depends_on: ["setup"]
  env:
    PULUMI_ACCESS_TOKEN: "${PULUMI_ACCESS_TOKEN}"
    AWS_DEFAULT_REGION: "us-west-2"
  command: |
    set -x
    if [ "$RELEASE" != "true" ]; then
      buildkite-agent artifact download pulumi-sdk.tgz
      buildkite-agent artifact download pulumi-resource-svmkit.tgz
      tar zxf pulumi-sdk.tgz
      tar zxf pulumi-resource-svmkit.tgz
      export PATH="$PWD/pulumi-svmkit/bin:$PATH"
    fi

    mkdir -p svmkit pulumi-svmkit

    ./tests/test-svmkit "$$TEST_NAME"

x-aws-test-template: &aws-test-template
    export PULUMI_ACCESS_TOKEN=$(buildkite-agent secret get PULUMI_ACCESS_TOKEN)
    export AWS_ACCESS_KEY_ID=$(buildkite-agent secret get AWS_ACCESS_KEY_ID)
    export AWS_SECRET_ACCESS_KEY=$(buildkite-agent secret get AWS_SECRET_ACCESS_KEY)
    <<*test-template
   
env:
#  SVMKIT_DIR:            "./svmkit"
#  PULUMI_SVMKIT_DIR:     "./pulumi-svmkit"
  SVMKIT_EXAMPLES_DIR:   .
  PULUMI_ACCESS_TOKEN:   "${PULUMI_ACCESS_TOKEN}"
  AWS_DEFAULT_REGION:    "us-west-2"
  RELEASE: true
  
steps:
  - key: setup
    label: ":rocket: Build svmkit and pulumi-svmkit"
    if: build.env("RELEASE") != "true"
    <<: *default-agents
    commands:
      - git clone https://github.com/abklabs/svmkit
      - git clone https://github.com/abklabs/pulumi-svmkit
      - tar zxf pulumi-sdk.tgz
      - export PULUMI_ACCESS_TOKEN=$(buildkite-agent secret get PULUMI_ACCESS_TOKEN)
      - export AWS_ACCESS_KEY_ID=$(buildkite-agent secret get AWS_ACCESS_KEY_ID) 
      - export AWS_SECRET_ACCESS_KEY=$(buildkite-agent secret get AWS_SECRET_ACCESS_KEY)       
      - ./tests/test-svmkit test-aws-network-spe-py

    commands:
      - git clone https://github.com/abklabs/svmkit     ./svmkit
      - git clone https://github.com/abklabs/pulumi-svmkit ./pulumi-svmkit
      - chmod +x ./tests/test-svmkit
      - echo Running test-svmkit --setup-only
      - ./tests/test-svmkit --setup-only
      - tar -zcf pulumi-sdk.tgz pulumi-svmkit/sdk pulumi-svmkit/bin
    artifact_paths:
      - pulumi-sdk.tgz
      - pulumi-resource-svmkit.tgz
      

  - label: ":heavy_check_mark: Test aws-network-spe-py"
    env:
      TEST_NAME: "test-aws-network-spe-py"
    <<: *aws-test-template

  - label: ":heavy_check_mark: Test aws-validator-fd-ts"
    env:
      TEST_NAME: "test-aws-validator-fd-ts"
    <<: *aws-test-template

  - label: ":heavy_check_mark: Test aws-validator-agave-ts"
    env:
      TEST_NAME: "test-aws-validator-agave-ts"
    <<: *aws-test-template
